# Generated by Django 3.1.2 on 2022-12-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221211_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='direccion',
        ),
    ]
